# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c4669cbc55054335ed2798bc41f05bf4cb6ce80fd80cf58488ed8bf45f8976593a1517e279b1b58e9da5d48d2ad41b99b584a8b849023c95a528ccab4a13123

test:
  secret_key_base: 282ea6bed654915d6c56e25bb10efd2bfa49da59599dc13a9855cc03be753b3c0407e1a5b4b8921041f9793ef312bd99773345afd2782a9691b58cb57dea9fc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
